spring.application.name=ingestion
logging.level.root=DEBUG

# User events
# ===============================
event.priority.user.login=LOW
event.priority.user.logout=LOW
event.priority.user.failed.login=HIGH
event.priority.user.multiple.failed.login=HIGH
event.priority.user.unauthorized=HIGH

# ===============================
# Payment events
# ===============================
event.priority.payment.success=MEDIUM
event.priority.payment.failed=HIGH

# ===============================
# Order events
# ===============================
event.priority.order.placed=MEDIUM
event.priority.order.cancelled=MEDIUM

# Resource Server configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-t3aad5tt8o4dhzde.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://agent-smith-api


logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.springframework.security.oauth2=TRACE
server.port=8087
