spring.application.name=ingestion
logging.level.root=DEBUG

# User events
# ===============================
event.priority.user.login=LOW
event.priority.user.logout=LOW
event.priority.user.failed.login=HIGH
event.priority.user.multiple.failed.login=HIGH
event.priority.user.unauthorized=HIGH

# ===============================
# Payment events
# ===============================
event.priority.payment.success=MEDIUM
event.priority.payment.failed=HIGH

# ===============================
# Order events
# ===============================
event.priority.order.placed=MEDIUM
event.priority.order.cancelled=MEDIUM
